### ISSUE TITLE
Reconstruct_color_from_graph

### ISSUE THREAD

**Issue by arletteespana** [david-schaller/bmg-edit#1]
Hi, I tried to use your tool and this message appears to me
![WhatsApp Image 2022-08-25 at 5 43 43 PM](https://user-images.githubusercontent.com/109096537/187767263-c2012285-8cad-4f98-8cb2-87bf7068f8db.jpeg)

**Comment by david-schaller** [comment]
Hi,
thanks! I have now merged the changes for AsymmeTree 2.2 support into the main branch which should fix this issue.
